# Generated by Django 3.1.2 on 2020-10-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moving_type', models.CharField(choices=[('move', 'Перемещение'), ('outgo', 'Расход')], max_length=12)),
                ('move_task', models.CharField(max_length=12)),
                ('move_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_from', to='ziponline.storage')),
                ('move_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to', to='ziponline.storage')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=70, verbose_name='Место'),
        ),
    ]
