# Generated by Django 3.1.2 on 2020-10-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0003_auto_20201004_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
        migrations.AddField(
            model_name='moving',
            name='move_good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_good', to='ziponline.good', verbose_name='Товар'),
        ),
    ]
