# Generated by Django 3.1.2 on 2020-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0005_auto_20201004_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moving',
            options={'verbose_name': 'Движение', 'verbose_name_plural': 'Движения'},
        ),
        migrations.AlterField(
            model_name='moving',
            name='move_date',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
    ]
