# Generated by Django 3.1.2 on 2020-10-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0006_auto_20201004_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='goods_min_remains',
        ),
        migrations.RemoveField(
            model_name='good',
            name='goods_now_remain',
        ),
        migrations.AddField(
            model_name='storage',
            name='good_min_remains',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Мин. Остаток'),
        ),
        migrations.AddField(
            model_name='storage',
            name='good_now_remain',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ziponline.good'),
        ),
        migrations.AlterField(
            model_name='good',
            name='goods_name',
            field=models.CharField(max_length=70, verbose_name='Наименование'),
        ),
    ]
