# Generated by Django 3.1.2 on 2020-10-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0008_auto_20201010_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='storage_good',
            new_name='goods_name',
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remains', models.PositiveSmallIntegerField(default=0, verbose_name='Остаток')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ziponline.good')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ziponline.storage')),
            ],
        ),
    ]
