# Generated by Django 3.1.2 on 2020-10-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0009_auto_20201010_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-storage'], 'verbose_name': 'Хранилище', 'verbose_name_plural': 'Хранилища (склад+товар)'},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='good_min_remains',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='good_now_remain',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='goods_name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='good_min_remains',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Мин. Остаток'),
        ),
    ]
