# Generated by Django 3.1.2 on 2020-10-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0010_auto_20201010_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_description',
            field=models.CharField(default='Добавьте описание', max_length=150, verbose_name='Описание'),
        ),
    ]
