# Generated by Django 3.1.2 on 2020-10-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0011_auto_20201010_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='goods_name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Наименование'),
        ),
    ]
