# Generated by Django 3.1.2 on 2020-10-13 21:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0012_auto_20201010_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moving',
            name='move_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sklA_num', models.PositiveSmallIntegerField(default=0, verbose_name='Ария')),
                ('sklA_num_min', models.PositiveSmallIntegerField(default=0, verbose_name='Ария мин.')),
                ('sklB_num', models.PositiveSmallIntegerField(default=0, verbose_name='Б+')),
                ('sklB_num_min', models.PositiveSmallIntegerField(default=0, verbose_name='Б+ мин.')),
                ('skaAU_num', models.PositiveSmallIntegerField(default=0, verbose_name='АиЮ')),
                ('sklAU_num_min', models.PositiveSmallIntegerField(default=0, verbose_name='АиЮ мин.')),
                ('sklSt_num', models.PositiveSmallIntegerField(default=0, verbose_name='АиЮ')),
                ('sklSt_num_min', models.PositiveSmallIntegerField(default=0, verbose_name='АиЮ мин.')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ziponline.good')),
            ],
        ),
    ]
