# Generated by Django 3.1.2 on 2020-10-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0013_auto_20201013_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sklad',
            options={'ordering': ['-good'], 'verbose_name': 'Товар на складах', 'verbose_name_plural': 'Товары на складах'},
        ),
        migrations.AddField(
            model_name='sklad',
            name='sklAU_num_app',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='АиЮ по актам'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='sklA_num_app',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ария по актам'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='sklB_num_app',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Базис+ по актам'),
        ),
        migrations.AddField(
            model_name='sklad',
            name='sklSt_num_app',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Старт по актам'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='sklSt_num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Старт'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='sklSt_num_min',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Старт мин.'),
        ),
    ]
