# Generated by Django 3.1.2 on 2020-10-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziponline', '0014_auto_20201013_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
